apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  labels:
    run: flink
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-job-service
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    jobmanager.heap.size: 1024m
    taskmanager.heap.size: 1024m
  log4j.properties: |+
    log4j.rootLogger=INFO, file
    log4j.logger.akka=INFO
    log4j.logger.org.apache.kafka=INFO
    log4j.logger.org.apache.hadoop=INFO
    log4j.logger.org.apache.zookeeper=INFO
    log4j.appender.file=org.apache.log4j.FileAppender
    log4j.appender.file.file=${log.file}
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    log4j.logger.org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline=ERROR, file

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    run: flink-job
  name: flink-job
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flink-job
  serviceName: flink-job-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flink-job
    spec:
      containers:
      - image: flink:latest
        name: flink-job
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/jobmanager.sh start;\
          while :;
          do
            if [[ -f $(find log -name '*jobmanager*.log' -print -quit) ]];
              then tail -f -n +1 log/*jobmanager*.log;
            fi;
          done"]
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        ports:
        - containerPort: 8081
        - containerPort: 6123
        - containerPort: 6124
        resources: {} 
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties

---
apiVersion: v1
kind: Service
metadata:
  name: flink-job-service
spec:
  type: NodePort
  ports:
  - port: 8081
    name: http
    targetPort: 8081
    nodePort: 32740
  - port: 6123
    name: rpc
    targetPort: 6123
    nodePort: 32739
  - port: 6124
    name: blob
    targetPort: 6124
    nodePort: 32738
  selector:
    run: flink-job

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: flink-task
  name: flink-task
spec:
  replicas: 2
  selector:
    matchLabels:
      run: flink-task
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flink-task
    spec:
      containers:
      - image: flink:latest
        name: flink-task
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/taskmanager.sh start; \
          while :;
          do
            if [[ -f $(find log -name '*taskmanager*.log' -print -quit) ]];
              then tail -f -n +1 log/*taskmanager*.log;
            fi;
          done"]
        ports:
        - containerPort: 6122
        resources: {} 
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
      initContainers:
        - name: init-job
          image: busybox
          command: ['sh', '-c', 'until nslookup flink-job-service; do echo waiting for flink-job-service; sleep 2; done;'] 
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flink-task-service
spec:
  type: NodePort
  ports:
  - port: 6122
    name: rpc
    targetPort: 6122
    nodePort: 32737

  selector:
    run: flink-task
