apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
      - name: kong-migration
        image: kong
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_PG_PASSWORD
            value: '123456'
          - name: KONG_PG_HOST
            value: 'postgres-service'
        command: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
      restartPolicy: Never
