apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kong
  name: kong
spec:
  replicas: 3
  selector:
    matchLabels:
      run: kong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kong
    spec:
      containers:
      - image: kong:latest
        name: kong
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "postgres-service"
        - name: KONG_PG_PASSWORD
          value: "123456"
        - name: KONG_CASSANDRA_CONTACT_POINTS
          value: "kong-database"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        ports:
        - containerPort: 8000
        - containerPort: 8443
        - containerPort: 8001
        - containerPort: 8444
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
spec:
  type: NodePort
  ports:
  - port: 8000
    name: web
    targetPort: 8000
    nodePort: 32758
  - port: 8001
    name: admin
    targetPort: 8001
    nodePort: 32757
  - port: 8443
    name: web-ssl
    targetPort: 8443
    nodePort: 32756
  - port: 8444
    name: admin-ssl
    targetPort: 8444
    nodePort: 32755
  selector:
    run: kong
