apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kudu
  name: kudu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kudu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kudu
    spec:
      containers:
      - image: usuresearch/kudu-docker-slim:release-v1.10.0-1
        env:
        - name: KUDU_MASTER_EXTRA_OPTS
          value: "--webserver_advertised_addresses 47.110.155.53:32722 --rpc_advertised_addresses 47.110.155.53:32724 --trusted_subnets 0.0.0.0/0 --rpc_encryption disabled --rpc_authentication disabled"
        - name: KUDU_TSERVER_EXTRA_OPTS
          value: "--webserver_advertised_addresses 47.110.155.53:32723 --rpc_advertised_addresses 47.110.155.53:32725 --trusted_subnets 0.0.0.0/0 --rpc_encryption disabled --rpc_authentication disabled --tserver_master_addrs 47.110.155.53:32724"
        ports:
        - containerPort: 7050
          name: tserver-rpc
        - containerPort: 7051
          name: master-rpc
        - containerPort: 8050
          name: tserver-web
        - containerPort: 8051
          name: master-web
        name: kudu
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kudu-service
spec:
  type: NodePort
  ports:
  - port: 7050
    targetPort: 7050
    nodePort: 32725
    name: tserver-rpc
  - port: 7051
    targetPort: 7051
    nodePort: 32724
    name: master-rpc
  - port: 8050
    nodePort: 32723
    targetPort: 8050
    name: tserver-web
  - port: 8051
    nodePort: 32722
    targetPort: 8051
    name: master-web
  selector:
    run: kudu
