apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: prometheus-blackbox-exporter
  name: prometheus-blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-blackbox-exporter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prometheus-blackbox-exporter
    spec:
      containers:
      - image: prom/blackbox-exporter
        name: prometheus-blackbox-exporter
        ports:
        - containerPort: 9115
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-exporter-service
spec:
  type: NodePort
  ports:
  - port: 9115
    name: web
    targetPort: 9115
    nodePort: 32746
  selector:
    run: prometheus-blackbox-exporter
