apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prometheus
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          subPath: prometheus.yml
        ports:
        - containerPort: 9090
        resources: {}
      volumes:
      - name: prometheus-config
        hostPath:
          path: /etc/prometheus
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  ports:
  - port: 9090
    name: web
    targetPort: 9090
    nodePort: 32750
  selector:
    run: prometheus
