apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: konga
  name: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      run: konga
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: konga
    spec:
      containers:
      - image: pantsel/konga:latest
        name: konga
        env:
        - name: TOKEN_SECRET
          value: "{{somerandomstring}}"
        ports:
        - containerPort: 1337
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: konga-service
spec:
  type: NodePort
  ports:
  - port: 1337
    targetPort: 1337
    nodePort: 32754
  selector:
    run: konga
